@startwbs domain
skinparam DefaultFontSize 20

* example.ru

** Компьютеры

*** Domain Computers
**** client.example.ru
*** Domain Controllers
**** dc.example.ru

** Пользователи

*** Генеральный директор

*** Отдел кадров
****:Руководитель 
отдела кадров ;
****  HR-специалист

*** Отдел продаж
****:Руководитель 
отдела продаж;
****:Специалист
по продажам;

*** Отдел ИТ
****:Руководитель
отдела ИТ;
****[#Salmon]:Системный
администратор;
****[#Salmon]:Системный
администратор;
****  Специалист по ИБ 

***:Производственное
подразделение;
****:Руководитель
подразделения;
****  Исполнитель 
****  Исполнитель 
****  Исполнитель 

*** Бухгалтерия
****:Главный
бухгалтер;
****  Бухгалтер




@endwbs