@startuml ifd

title Информационные потоки типового предприятия

skinparam defaultFontName Helvetica
skinparam BoxPadding 5
skinparam TitleFontSize 40
skinparam DefaultFontSize 30
skinparam ArrowThickness 3

box "Типовое предприятие" #f0f0f0
participant "Отдел продаж" as sales
participant "Бухгалтерия" as accounting
participant "Отдел кадров" as hr
participant "Генеральный директор" as ceo
participant "Производственное\nподразделение" as production
participant "Отдел ИТ" as it
end box

==Оплата труда==

hr -> accounting : Информация о сверхурочной работе
hr -> ceo : Информация о сотрудниках, подлежащих премированию
group #ffdbdb Коммерческая тайна
    ceo -> accounting : Приказ о назначении премии
    accounting -> sales : Информация о начислении з/п
    accounting -> accounting : Информация о начислении з/п
    accounting -> hr : Информация о начислении з/п
    accounting -> ceo : Информация о начислении з/п
    accounting -> production : Информация о начислении з/п
    accounting -> it : Информация о начислении з/п
end

==Техническая поддержка==

production -> it : Заявки на тех. поддержку
it -> production : Ответ на заявку
ceo -> it : Заявки на тех. поддержку
it -> ceo : Ответ на заявку
hr -> it : Заявки на тех. поддержку
it -> hr : Ответ на заявку
accounting -> it : Заявки на тех. поддержку
it -> accounting : Ответ на заявку
sales -> it : Заявки на тех. поддержку
it -> sales : Ответ на заявку

@enduml