@startuml ifd

title Информационные потоки типового предприятия

skinparam ParticipantPadding 10
skinparam BoxPadding 10
skinparam DefaultFontSize 20
skinparam TitleFontSize 30

box "Внешние сущности" #LightBlue 
participant "Клиент" as client
participant "Налоговая служба" as irs
participant "Соискатель/\nСотрудник" as candidate
end box

box "Типовое предприятие" #LightGreen
participant "Отдел продаж" as sales
participant "Бухгалтерия" as accounting
participant "Отдел кадров" as hr
participant "Генеральный директор" as ceo
participant "Производственное\nподразделение" as production
participant "Отдел ИТ" as it
end box

==Кадровая работа==

group #LightGray Приём на работу  
    candidate -> hr : Резюме
    hr -> candidate : Информация о прохождении собеседования
    group #Salmon ПДн соискателей
        candidate -> hr : Пакет документов
    end
    hr -> ceo : Информация о кандидатах
    ceo -> hr : Приказы о приёме на работу
    hr -> candidate : Информация о приёме на работу
end

group #LightGray Учёт сотрудников и увольнение  
    group #Salmon ПДн сотрудников
        hr -> accounting : Информация о новых сотрудниках
        hr -> it : Информация о новых сотрудниках
    end
    it -> candidate : Учётные данные в корпоративных ресурсах
    candidate -> hr : Заявление об увольнении
    hr -> ceo : Сведения об увольняемых сотрудниках
    ceo -> hr : Приказы об увольнении
    hr -> accounting : Информация об уволенных сотрудниках
    hr -> it : Информация об уволенных сотрудниках
end

==Деятельность предприятия==
group #LightGrey Предоставление услуг
    client -> sales : Заявка и техническое задание
    sales -> production : Техническое задание
    production -> sales : Обратная связь по ТЗ
    sales -> client : Обратная связь по ТЗ
    client -> sales : Согласованное ТЗ
    group #Salmon Коммерческая тайна
        client -> sales : Договор
        sales -> ceo : Договор с клиентом
        ceo -> sales : Подписанный договор
        sales -> client : Подписанный договор
    end
    sales -> production : Согласованное ТЗ
    sales -> production : Информация о начале работ
    production -> sales : Информация о выполненных работах
    sales -> client : Информация о выполненных работах
    group #Salmon Коммерческая тайна
        client -> sales : Информация об оплате по договору
    end

end
group #Salmon Коммерческая тайна
    sales -> accounting : Информация о проведённых сделках
    accounting -> ceo : Финансовая отчётность
end
accounting -> irs : Информация об уплате налогов
group #Salmon Отчётность по ИБ
    it -> ceo : Отчётность об обработке\nперсональных данных
    it -> ceo : Отчётность об обработке\nкоммерческой тайны
end

group #LightGray Поддержка и развитие ИТ и ИБ
    it -> ceo : Предложения по усовершенствованию ИТ-инфраструктуры
    ceo -> it : Приказ об усовершенствованию ИТ-инфраструктуры
    group #Salmon Коммерческая тайна
        it -> accounting : Запрос средств на реализацию проектов
        accounting -> it : Информация о выделенных средствах
    end
    it -> ceo : Отчётность по поддержке и усовершенствованию ИТ
    group #Salmon Коммерческая тайна
        it -> ceo : Предложения по реализации мер ИБ и внедрению СЗИ
        ceo -> it : Приказ о реализации мер ИБ и внедрению СЗИ
        it -> accounting : Запрос средств на реализацию проектов
        accounting -> it : Информация о выделенных средствах
        it -> ceo : Отчётность по поддержке и усовершенствованию ИБ
    end
end

==Оплата труда==

hr -> accounting : Информация о сверхурочной работе
hr -> ceo : Информация о сотруднках, подлежащих премированию
group #Salmon Коммерческая тайна
    ceo -> accounting : Приказ о назначении премии
    accounting -> sales : Информация о начислении з/п
    accounting -> accounting : Информация о начислении з/п
    accounting -> hr : Информация о начислении з/п
    accounting -> ceo : Информация о начислении з/п
    accounting -> production : Информация о начислении з/п
    accounting -> it : Информация о начислении з/п
end

==Техническая поддержка==

production -> it : Заявки на тех. поддержку
it -> production : Ответ на заявку
ceo -> it : Заявки на тех. поддержку
it -> ceo : Ответ на заявку
hr -> it : Заявки на тех. поддержку
it -> hr : Ответ на заявку
accounting -> it : Заявки на тех. поддержку
it -> accounting : Ответ на заявку
sales -> it : Заявки на тех. поддержку
it -> sales : Ответ на заявку

@enduml