@startuml model


|pfsense|
start
:Создание и настройка\nвиртуальной машины\nв гипервизоре;
|dc|
:Создание и настройка\nвиртуальной машины\nв гипервизоре;
|client|
:Создание и настройка\nвиртуальной машины\nв гипервизоре;

|pfsense|
:Установка ОС pfSense\nна виртуальную машину;
:Настройка IP-адресов\nсетевых интерфейсов;
:Конфигурация DHCP\nв локальной сети;
:Конфигурация DNS;

|dc|
:Установка Astra Linux SE 1.7\nна виртуальную машину;
:Настройка доменного имени ВМ;
:Установка пакета ald-server;
:Первичная конфигурация\nслужбы каталогов;
:Создание групп домена;
:Создание парольных политик;
:Создание пользователей домена;
:Установка привилегий;

|client|
:Установка Astra Linux SE 1.7\nна виртуальную машину;
:Настройка доменного\nимени ВМ;
:Установка клиентского ПО\nслужбы каталогов;
:Включение машины в домен;

|dc|
:Выдача доступа к\nкомпьютеру пользователям;

|client|
:Вход под УЗ доменного\nпользователя;
:Тестирование службы\nкаталогов;
end 
@enduml