@startuml model

start
:Установка Astra Linux SE 1.7;
if (ald был установлен при установке ОС?) then (да)
else (нет)
:Установка пакета ald;
endif
:Конфигурация ald;
:Создание схемы LDAP;
:Заполнение БД;
:Конфигурация клиентов;
:Тестирование службы каталогов;
end 
@enduml