@startuml model

start
:Установка и конфигурация ВМ PfSense;
:Установка Astra Linux SE 1.7 на ВМ КД и клиентов;
fork
:Установка пакета ald;
:Конфигурация ald;
:Создание схемы LDAP;
:Заполнение БД;
fork again
:Конфигурация клиентов;
end fork
:Тестирование службы каталогов;
end 
@enduml