@startuml network

nwdiag {
    internet [shape = cloud, description="Интернет"]
    internet -- pfsense
    network ЛВС {
        pfsense [address = "192.168.14.1", description="pfsense.example.ru\nМаршрутизатор + DNS"]
        address = "192.168.14.0/24"

        dc [address = "192.168.14.50", description="Контроллер домена\ndc.example.ru"]
        client [address = "192.168.14.x", description="Клиент\nclient.example.ru"]
    }
}

@enduml