@startwbs orgchart

skinparam DefaultFontSize 20

* Генеральный директор

** Отдел продаж
***:Руководитель 
отдела продаж;
***:Специалист
по продажам;

** Бухгалтерия 
***:Главный
бухгалтер;
***  Бухгалтер

** Отдел кадров 
***:Руководитель 
отдела кадров ;
***  HR-специалист 

**:Производственное
подразделение;
***:Руководитель
подразделения;
***  Исполнитель 
***  Исполнитель 
***  Исполнитель 

** Отдел ИТ 
***:Руководитель
отдела ИТ;
***:Системный
администратор;
***:Системный
администратор;
***  Специалист по ИБ 

@endwbs