@startwbs orgchart

*[#Salmon] Генеральный директор

**[#LightGreen] Отдел продаж
***[#LightBlue]:Руководитель 
отдела продаж;
***[#LightBlue]:Специалист
по продажам;

**[#LightGreen] Бухгалтерия 
***[#LightBlue]:Главный
бухгалтер;
***[#LightBlue]  Бухгалтер

**[#LightGreen] Отдел кадров 
***[#LightBlue]:Руководитель 
отдела кадров ;
***[#LightBlue]  HR-специалист 

**[#LightGreen]:Производственное
подразделение;
***[#LightBlue]:Руководитель
подразделения;
***[#LightBlue]  Исполнитель 
***[#LightBlue]  Исполнитель 
***[#LightBlue]  Исполнитель 

**[#LightGreen] Отдел ИТ 
***[#LightBlue]:Руководитель
отдела ИТ;
***[#LightBlue]:Системный
администратор;
***[#LightBlue]:Системный
администратор;
***[#LightBlue]  Специалист по ИБ 

@endwbs